// english-sena-project/src/Components/Description.jsx
import React from "react";
import styled from "styled-components";

const TitlePadding = styled.h1`
  padding-bottom: 50px;
`;

export function Description({ title, description }) {
  return (
    <section className="section">
      <div className="container">
        <TitlePadding className="title has-text-centered">{title}</TitlePadding>
        <p className="subtitle">{description}</p>
      </div>
    </section>
  );
}

// english-sena-project/src/components/description.svelte
<script>
  export let title;
  export let description;
</script>

<style>
  .title-padding {
    padding-bottom: 50px;
  }
</style>

<section class="section">
  <div class="container">
    <h1 class="title has-text-centered title-padding">{title}</h1>
    <p class="subtitle">{description}</p>
  </div>
</section>
