// english-sena-project/src/layout/header.svelte
<script>
  import { Link } from "svelte-routing";

  let isOpen = false;

  function handleMenuOpen() {
    isOpen = !isOpen;
  }
</script>

<style>
  .navbar-item:hover {
    cursor: pointer;
    background-color: #fafafa;
  }
</style>

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="/favicon.png" width="112" height="58" alt="" />
    </a>

    <span
      on:click={() => handleMenuOpen()}
      role="button"
      class="navbar-burger burger {isOpen && 'is-active'}"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbarBasicExample">
      <span aria-hidden="true" />
      <span aria-hidden="true" />
      <span aria-hidden="true" />
    </span>
  </div>

  <div id="navbarBasicExample" class="navbar-menu {isOpen && 'is-active'}">
    <div class="navbar-end">
      <div class="navbar-item has-dropdown is-hoverable">
        <span class="navbar-link">Useful vocabulary</span>

        <div class="navbar-dropdown">
          <Link to="/">
            <span class="navbar-item">Sports</span>
          </Link>
          <Link to="/actions">
            <span class="navbar-item">Actions</span>
          </Link>
        </div>
      </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <span class="navbar-link">General vocabulary review</span>

        <div class="navbar-dropdown">
          <Link to="/fruits">
            <span class="navbar-item">Fruits</span>
          </Link>
          <Link to="/color">
            <span class="navbar-item">Color</span>
          </Link>
          <Link to="/animals">
            <span class="navbar-item">Animals</span>
          </Link>
        </div>
      </div>
    </div>
  </div>
</nav>

// english-sena-project/src/Layout/Header.jsx
import React, { useState } from "react";
import { Link } from "@reach/router";
import styled from "styled-components";

const NavbarItem = styled.span`
  &:hover {
    cursor: pointer;
    background-color: #fafafa;
  }
`;

export function Header() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <nav className="navbar" role="navigation" aria-label="main navigation">
      <div className="navbar-brand">
        <a className="navbar-item" href="/">
          <img src="/favicon.png" width="112" height="58" alt="" />
        </a>

        <span
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          role="button"
          className={`navbar-burger burger ${isMenuOpen ? "is-active" : ""}`}
          aria-label="menu"
          aria-expanded="false"
          data-target="navbarBasicExample"
        >
          <span aria-hidden="true" />
          <span aria-hidden="true" />
          <span aria-hidden="true" />
        </span>
      </div>

      <div
        id="navbarBasicExample"
        className={`navbar-menu ${isMenuOpen ? "is-active" : ""}`}
      >
        <div className="navbar-end">
          <div className="navbar-item has-dropdown is-hoverable">
            <span className="navbar-link">Useful vocabulary</span>

            <div className="navbar-dropdown">
              <Link to="/" onClick={() => setIsMenuOpen(false)}>
                <NavbarItem className="navbar-item">Sports</NavbarItem>
              </Link>
              <Link to="/actions" onClick={() => setIsMenuOpen(false)}>
                <NavbarItem className="navbar-item">Actions</NavbarItem>
              </Link>
            </div>
          </div>

          <div className="navbar-item has-dropdown is-hoverable">
            <span className="navbar-link">General vocabulary review</span>

            <div className="navbar-dropdown">
              <Link to="/fruits" onClick={() => setIsMenuOpen(false)}>
                <NavbarItem className="navbar-item">Fruits</NavbarItem>
              </Link>
              <Link to="/color" onClick={() => setIsMenuOpen(false)}>
                <NavbarItem className="navbar-item">Color</NavbarItem>
              </Link>
              <Link to="/animals" onClick={() => setIsMenuOpen(false)}>
                <NavbarItem className="navbar-item">Animals</NavbarItem>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
}
