// english-sena-project/src/pages/actions.svelte
<script>
  import Description from "../components/description.svelte";
</script>

<Description
  title="Actions Game"
  description="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi
  reprehenderit voluptatem error, eos distinctio pariatur velit, nobis minus
  optio quaerat quia modi officia ex quisquam illo soluta blanditiis, alias
  fuga!" />

// english-sena-project/src/Pages/actions.jsx
import React from "react";

import { Description } from "../Components/Description";

function ActionsGame() {
  return (
    <Description
      title="Actions Game"
      description="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi
  reprehenderit voluptatem error, eos distinctio pariatur velit, nobis minus
  optio quaerat quia modi officia ex quisquam illo soluta blanditiis, alias
  fuga!"
    />
  );
}

export default ActionsGame;
