// english-sena-project/src/Pages/color.jsx
import React from "react";

import { Description } from "../Components/Description";
import { Color } from "../Components/Color";

function ColorGame() {
  return (
    <>
      <Description
        title="Color Game"
        description="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi
    reprehenderit voluptatem error, eos distinctio pariatur velit, nobis minus
    optio quaerat quia modi officia ex quisquam illo soluta blanditiis, alias
    fuga!"
      />

      <Color />
    </>
  );
}

export default ColorGame;

// english-sena-project/src/pages/color.svelte
<script>
  import Description from "../components/description.svelte";
</script>

<Description
  title="Color Game"
  description="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Animi
  reprehenderit voluptatem error, eos distinctio pariatur velit, nobis minus
  optio quaerat quia modi officia ex quisquam illo soluta blanditiis, alias
  fuga!" />
